[".local/share/zinit/zinit.git"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"

["source/repos/rofi"]
    type = "git-repo"
    url = "https://github.com/adi1090x/rofi.git"

[".dotfiles/"]
    type = "git-repo"
    url = "git@github.com:dcheld/zfiles.git"

[".vim/"]
    type = "git-repo"
    url = "git@github.com:dcheld/vimfiles.git"
